CREATE TABLE USER
(
  CODE_USER     VARCHAR(5)              NOT NULL,
  NOM    VARCHAR(40),
  PRENOM VARCHAR(40),
  EMAIL  VARCHAR(40),
  MOT_DE_PASSE     VARCHAR(100)
);

ALTER TABLE USER ADD 
  PRIMARY KEY
  (CODE_USER);
